### ISSUE TITLE
ansible task failed at "Edit Networking"

### ISSUE THREAD

**Issue by laceth** [OpenStackCookbook/vagrant-openstack#28]
Error: 
fatal: [controller-01]: FAILED! => {"changed": true, "cmd": "/va grant/networking.sh", "delta": "0:00:05.563110", "end": "2018-05-05 03:19:27.152319", "msg": "non-zero return code", "rc": 1, "s                                         tart": "2018-05-05 03:19:21.589209", "stderr": "eth1: error fetching interface information: Device not found\nUnknown interface eth1\nUnknown interface eth2\nUnknown interface eth3\nUnknown in                                         terface eth4\ninterface eth1 does not exist!\nError: ??? prefix is expected rather than \"172.29.236./255.255.255.0\".\ninterfac

Look into the VM controller-01 network interface file and saw interface names where 
enp0s8,enp0s9, enp0s10 and enp0s11 
Therefore naminng convention is different from the network.sh file that using typical naming convention, eth0,eth1,eth2,etc. 
How to fix this ? Do I need to edit network.sh file with what in VM controller-01 and compute-01 ?

**Comment by laceth** [comment]
Forgot to mention:
ubuntu/xenial64 vagrant box used (gave above error on network interface) since velocity/xenial64 is not longer on the vagrant cloud.
went ahead and updated the interfaces in the VMs with regular naming convention (eth1,eth2,etc)
and will reprovision to see if that work with ansible playbook.

**Comment by uksysadmin** [comment]
Can you describe the host OS, version of Vagrant, version of VirtualBox that you're using? I was able to complete a vagrant up of this environment on Thursday but your error seems to show output of various networking devices that are not inline with what I see which suggests you're using something other than the Xenial box image that we specify (related to your other bug).

**Comment by laceth** [comment]
correct go the correct version box now, somehow I was using wrong path to cloud. thanks

**Comment by laceth** [comment]
Thanks updated the issue and got the corrent vagrant 2.0.2 and now testing that version for installation. before was using vagrant 2.1.thanks for reply back. 
Tarik Riley512 750 9694 

    On Saturday, May 5, 2018, 11:39:07 AM EDT, Kevin Jackson <notifications@github.com> wrote:  
 
 
Can you describe the host OS, version of Vagrant, version of VirtualBox that you're using? I was able to complete a vagrant up of this environment on Thursday but your error seems to show output of various networking devices that are not inline with what I see which suggests you're using something other than the Xenial box image that we specify (related to your other bug).

**Comment by laceth** [comment]
you can close this . Got the right box name. thanks
