### ISSUE TITLE
Support for nfsd need to be enabled on Linux host

### ISSUE THREAD

**Issue by it-praktyk** [OpenStackCookbook/vagrant-openstack#3]
Looks like additional requirements need to be added to the list in the README.md document.

Maybe except that you can add
- instruction what need to be supported on used boxes
- instruction how use other than NFS type of sharing folders between boxes and the a host

My software
- Fedora Linux 25 x86, kernel 4.11.10-200.fc25.x86_64
- Vagrant 1.9.7
- Vagrant plugins:
  - vagrant-dsc (2.0.0)
  - vagrant-hostmanager (1.8.7)
  - vagrant-scp (0.5.7)
  - vagrant-share (1.1.9, system)
  - vagrant-triggers (0.5.3)
  - vagrant-vmware-workstation (4.0.22)
- VMware Workstation 12.5.7 build-5813279

```
==> compute-01: Cloning VMware VM: 'velocity42/xenial64'. This can take some time...
==> compute-01: Checking if box 'velocity42/xenial64' is up to date...
==> compute-01: Verifying vmnet devices are healthy...
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

**Comment by it-praktyk** [comment]
@adfinlay , @InvertedAcceleration do you share somewhere the Packer project for the box [velocity42/xenial64]https://app.vagrantup.com/velocity42/boxes/xenial64?

**Comment by adfinlay** [comment]
@it-praktyk the project is available at https://github.com/adfinlay/packer-ubuntu-1604 - pull requests welcome

**Comment by it-praktyk** [comment]
@adfinlay ,
I did https://github.com/geerlingguy/packer-ubuntu-1604/pull/22 - now I wait for approval by @geerlingguy.

If you plan build in the new future please be aware https://github.com/geerlingguy/ansible-role-packer-debian/issues/16.

**Comment by uksysadmin** [comment]
Thanks for noting this. We'll add this to the list of assumptions/requirements.
