### ISSUE TITLE
set-host-error

### ISSUE THREAD

**Issue by kobehaha** [OpenStackCookbook/vagrant-openstack#31]
TASK [runplaybooks : Running openstack-ansible setup-hosts.yml] ****************
fatal: [controller-01]: FAILED! => {"changed": true, "cmd": "openstack-ansible --forks 1 setup-hosts.yml -v > /vagrant/logs/setup-hosts-fallback.log", "delta": "0:01:18.327643", "end": "2018-05-06 05:52:22.495090", "msg": "non-zero return code", "rc": 2, "start": "2018-05-06 05:51:04.167447", "stderr": " [WARNING]: when statements should not include jinja2 templating delimiters\nsuch as {{ }} or {% %}. Found: {{ result.rc not in [0, 2] }}\n [WARNING]: when statements should not include jinja2 templating delimiters\nsuch as {{ }} or {% %}. Found: {{ result.rc not in [0, 2] }}", "stderr_lines": [" [WARNING]: when statements should not include jinja2 templating delimiters", "such as {{ }} or {% %}. Found: {{ result.rc not in [0, 2] }}", " [WARNING]: when statements should not include jinja2 templating delimiters", "such as {{ }} or {% %}. Found: {{ result.rc not in [0, 2] }}"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
compute-01                 : ok=13   changed=7    unreachable=0    failed=0
controller-01              : ok=22   changed=15   unreachable=0    failed=2
openstack-client           : ok=15   changed=7    unreachable=0    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by it-praktyk** [comment]
Please attach - preferably as links to separate gists - logs. 

You can find them in the subfolder logs inside the project folder.

**Comment by kobehaha** [comment]
thanks for you reply , but I change the method for deploying  openstack by other ways
