### ISSUE TITLE
fatal: [controller-01]: FAILED! - python_version == \"3.5\"' don't match your environment - ERROR: You must give at least one requirement to install (see \"pip help install

### ISSUE THREAD

**Issue by am-abbasi** [OpenStackCookbook/vagrant-openstack#32]
Hello,

I've faced the following issue during the installation, here is the log from "setup-hosts.log" file.

TASK [Create the LXC service log aggregation link] *****************************
Monday 14 May 2018  14:08:55 +0000 (0:00:00.817)       0:02:00.186 ************ 
changed: [controller-01]

TASK [apt_package_pinning : Add apt pin preferences] ***************************
Monday 14 May 2018  14:08:56 +0000 (0:00:00.838)       0:02:01.025 ************ 

TASK [pip_install : Gather variables for each operating system] ****************
Monday 14 May 2018  14:08:56 +0000 (0:00:00.041)       0:02:01.067 ************ 
ok: [controller-01] => (item=/etc/ansible/roles/pip_install/vars/ubuntu-16.04.yml)

TASK [pip_install : Remove unneeded files from previous releases] **************
Monday 14 May 2018  14:08:57 +0000 (0:00:00.760)       0:02:01.827 ************ 
ok: [controller-01] => (item=/root/.pip/base)
ok: [controller-01] => (item=/root/.pip/links.d)
ok: [controller-01] => (item=/root/.pip/pip-link-build.py)

TASK [pip_install : Create pip config directory] *******************************
Monday 14 May 2018  14:08:58 +0000 (0:00:01.517)       0:02:03.344 ************ 
ok: [controller-01] => (item=/root/.cache)
ok: [controller-01] => (item=/root/.cache/pip)
changed: [controller-01] => (item=/root/.pip)

TASK [pip_install : Drop pip config] *******************************************
Monday 14 May 2018  14:08:59 +0000 (0:00:01.422)       0:02:04.767 ************ 
changed: [controller-01]

TASK [pip_install : Remove known problem packages] *****************************
Monday 14 May 2018  14:09:00 +0000 (0:00:01.006)       0:02:05.773 ************ 
ok: [controller-01]

TASK [pip_install : include] ***************************************************
Monday 14 May 2018  14:09:02 +0000 (0:00:01.621)       0:02:07.394 ************ 
included: /etc/ansible/roles/pip_install/tasks/pre_install_apt.yml for controller-01

TASK [pip_install : Install UCA repository key] ********************************
Monday 14 May 2018  14:09:02 +0000 (0:00:00.196)       0:02:07.591 ************ 
changed: [controller-01]

TASK [pip_install : Install UCA repository] ************************************
Monday 14 May 2018  14:09:20 +0000 (0:00:17.370)       0:02:24.962 ************ 
changed: [controller-01]

TASK [pip_install : Install external repo key manually (apt)] ******************
Monday 14 May 2018  14:09:42 +0000 (0:00:22.107)       0:02:47.070 ************ 

TASK [pip_install : Install external repo manually (apt)] **********************
Monday 14 May 2018  14:09:42 +0000 (0:00:00.084)       0:02:47.155 ************ 

TASK [pip_install : Install distro packages] ***********************************
Monday 14 May 2018  14:09:42 +0000 (0:00:00.107)       0:02:47.262 ************ 
ok: [controller-01]

TASK [pip_install : include] ***************************************************
Monday 14 May 2018  14:09:47 +0000 (0:00:05.227)       0:02:52.489 ************ 
included: /etc/ansible/roles/pip_install/tasks/install_online.yml for controller-01

TASK [pip_install : Get Modern PIP] ********************************************
Monday 14 May 2018  14:09:47 +0000 (0:00:00.163)       0:02:52.653 ************ 
ok: [controller-01]

TASK [pip_install : include] ***************************************************
Monday 14 May 2018  14:10:23 +0000 (0:00:35.537)       0:03:28.191 ************ 
included: /etc/ansible/roles/pip_install/tasks/install_source.yml for controller-01

TASK [pip_install : Install PIP] ***********************************************
Monday 14 May 2018  14:10:23 +0000 (0:00:00.332)       0:03:28.523 ************ 
changed: [controller-01]

TASK [pip_install : Install pip packages] **************************************
Monday 14 May 2018  14:11:02 +0000 (0:00:38.481)       0:04:07.005 ************ 
FAILED - RETRYING: Install pip packages (5 retries left).
FAILED - RETRYING: Install pip packages (4 retries left).
FAILED - RETRYING: Install pip packages (3 retries left).
FAILED - RETRYING: Install pip packages (2 retries left).
FAILED - RETRYING: Install pip packages (1 retries left).
fatal: [controller-01]: FAILED! => {"attempts": 5, "changed": false, "cmd": "/usr/local/bin/pip2 install -U --constraint /opt/global-requirement-pins.txt --constraint https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?id=e10c17726f5c43eb0b8ffb89013447affb794da9 --trusted-host 172.29.236.10 ", "failed": true, "msg": "stdout: Ignoring jsbeautifier: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring jsbeautifier: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring hyperframe: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring hyperframe: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring cssutils: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring cssutils: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring kaitaistruct: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring kaitaistruct: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring tornado: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring tornado: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring ruamel.yaml: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring ruamel.yaml: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring html2text: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring html2text: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring dnspython3: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring dnspython3: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring hpack: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring hpack: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring brotlipy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring brotlipy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring mypy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring mypy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring urwid: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring urwid: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring argh: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring argh: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring blinker: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring blinker: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring typed-ast: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring typed-ast: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring h2: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring h2: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring mitmproxy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring mitmproxy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring EditorConfig: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring EditorConfig: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring watchdog: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring watchdog: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring backports-abc: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring backports-abc: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring pathtools: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring pathtools: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring sortedcontainers: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring sortedcontainers: markers 'python_version == \"3.5\"' don't match your environment\n\n:stderr: ERROR: You must give at least one requirement to install (see \"pip help install\")\n"}

TASK [pip_install : Install pip packages (fall back mode)] *********************
Monday 14 May 2018  14:11:24 +0000 (0:00:22.497)       0:04:29.502 ************ 
FAILED - RETRYING: Install pip packages (fall back mode) (5 retries left).
FAILED - RETRYING: Install pip packages (fall back mode) (4 retries left).
FAILED - RETRYING: Install pip packages (fall back mode) (3 retries left).
FAILED - RETRYING: Install pip packages (fall back mode) (2 retries left).
FAILED - RETRYING: Install pip packages (fall back mode) (1 retries left).
fatal: [controller-01]: FAILED! => {"attempts": 5, "changed": false, "cmd": "/usr/local/bin/pip2 install -U --isolated --constraint /opt/global-requirement-pins.txt --constraint https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?id=e10c17726f5c43eb0b8ffb89013447affb794da9 --trusted-host 172.29.236.10 ", "failed": true, "msg": "stdout: Ignoring jsbeautifier: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring jsbeautifier: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring hyperframe: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring hyperframe: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring cssutils: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring cssutils: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring kaitaistruct: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring kaitaistruct: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring tornado: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring tornado: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring ruamel.yaml: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring ruamel.yaml: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring html2text: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring html2text: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring dnspython3: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring dnspython3: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring hpack: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring hpack: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring brotlipy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring brotlipy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring mypy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring mypy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring urwid: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring urwid: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring argh: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring argh: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring blinker: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring blinker: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring typed-ast: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring typed-ast: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring h2: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring h2: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring mitmproxy: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring mitmproxy: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring EditorConfig: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring EditorConfig: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring watchdog: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring watchdog: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring backports-abc: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring backports-abc: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring pathtools: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring pathtools: markers 'python_version == \"3.5\"' don't match your environment\nIgnoring sortedcontainers: markers 'python_version == \"3.4\"' don't match your environment\nIgnoring sortedcontainers: markers 'python_version == \"3.5\"' don't match your environment\n\n:stderr: ERROR: You must give at least one requirement to install (see \"pip help install\")\n"}

NO MORE HOSTS LEFT *************************************************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
compute-01                 : ok=22   changed=13   unreachable=0    failed=0   
controller-01              : ok=48   changed=22   unreachable=0    failed=2   

Monday 14 May 2018  14:11:48 +0000 (0:00:23.909)       0:04:53.412 ************ 
=============================================================================== 
openstack_hosts : Install distro packages ------------------------------ 55.35s
pip_install : Install PIP ---------------------------------------------- 38.48s
pip_install : Get Modern PIP ------------------------------------------- 35.54s
pip_install : Install pip packages (fall back mode) -------------------- 23.91s
pip_install : Install pip packages ------------------------------------- 22.50s
pip_install : Install UCA repository ----------------------------------- 22.11s
pip_install : Install UCA repository key ------------------------------- 17.37s
openstack_hosts : Drop hosts file entries script locally --------------- 12.34s
openstack_hosts : Ensure kernel module(s) ------------------------------- 7.96s
openstack_hosts : Adding new system tuning ------------------------------ 7.91s
pip_install : Install distro packages ----------------------------------- 5.23s
Gathering Facts --------------------------------------------------------- 2.43s
openstack_hosts : Copy templated hosts file entries script -------------- 2.23s
openstack_hosts : Restart sysstat --------------------------------------- 2.16s
openstack_hosts : Enable sysstat config --------------------------------- 1.81s
openstack_hosts : Remove conflicting distro packages -------------------- 1.74s
pip_install : Remove known problem packages ----------------------------- 1.62s
Test internal repo URL for the current get-pip.py script ---------------- 1.58s
openstack_hosts : Write list of modules to load at boot ----------------- 1.55s
pip_install : Remove unneeded files from previous releases -------------- 1.52s

**Comment by uksysadmin** [comment]
This appears to be related to a later version of Python - which shouldn't be feasible? The VMs should be using Xenial 16.04 (https://github.com/OpenStackCookbook/vagrant-openstack/blob/master/Vagrantfile#L33)

Have you modified any of the files before launching a vagrant up?

Let me know the host OS, the version of Vagrant, VirtualBox (or VMware - whichever you're choosing)?

Thanks,
Kev

**Comment by am-abbasi** [comment]
I've followed the steps in the book exactly, all of the versions should be
similar but I will provide you with the details soon.

Thank you for your assistance.

**Comment by am-abbasi** [comment]
Hello,

Nothing has changed before the installation. I've copied the steps in the
link below:
https://paste.ubuntu.com/p/XCz3N7jKQw/


Here is the details of my host:

root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

root@ubuntu:~# vagrant -v
Vagrant 2.0.1


root@ubuntu:~# dpkg -l|grep -i virtualbox
ii  virtualbox-5.1                       5.1.38-122592~Ubuntu~xenial
        amd64        Oracle VM VirtualBox

**Comment by bunchc** [comment]
I think @uksysadmin this is related to the vagrant ansible provisioner. 

@am-abbasi Can you provide the outputs of the following:

**On the host:**
* vagrant --version
* ansible --version
* python --version

**In the VM**
* python --version

**Comment by bunchc** [comment]
Note to self, I've started this running, will check it in a bit:

```
root@lab-a:~/projects/vagrant-openstack# vagrant --version
Vagrant 2.0.2
root@lab-a:~/projects/vagrant-openstack# python --version
Python 2.7.12
root@lab-a:~/projects/vagrant-openstack# ansible --version
ansible 2.5.0
  config file = /root/projects/vagrant-openstack/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
