### ISSUE TITLE
Does vagrant-openstack suppose to work on Windows too?

### ISSUE THREAD

**Issue by it-praktyk** [OpenStackCookbook/vagrant-openstack#4]
I'm interested if you planned to support vagrant-openstack on Windows too.

When I tried run it on Windows Server 2012 R2 (I just had powerful server) and VirtualBox I've received error

```
==> controller-01: Running provisioner: shell...
    controller-01: Running: C:/Users/ADMINI~1/AppData/Local/Temp/2/vagrant-shell20170809-3152-y5u2p2.sh
==> controller-01: Running provisioner: ansible...
Windows is not officially supported for the Ansible Control Machine.
Please check https://docs.ansible.com/intro_installation.html#control-machine-requirements
    controller-01: Running ansible-playbook...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your host system.

If you haven't installed Ansible yet, please install Ansible
on your host system. Vagrant can't do this for you in a safe and
automated way.
Please check https://docs.ansible.com for more information.
```

An issue probably can be resolved easily by adding two shell provisioners
1. install Ansible inside of controller-01 - e.g. https://github.com/geerlingguy/packer-ubuntu-1604/blob/master/scripts/ansible.sh
2. run Ansible playbook inside of controller-01

**Comment by it-praktyk** [comment]
The better example how to install Ansible via script: https://github.com/it-praktyk/packer-ubuntu-1604/blob/3f5f2805e1aa4faa04110ae3064858699ae492c2/scripts/ansible.sh

**Comment by uksysadmin** [comment]
Our priority is currently to get the book written, which this environment is an additional helper environment to help you work through it - and our development environments are predominantly Linux or MacOS/OSX based. We do intend to have this working for Windows and we appreciate any fixes which we will test when we get chance.
